version: '3.8'

services:
  grafana:
    container_name: 'grafana'
    image: 'grafana/grafana'
    restart: 'unless-stopped'
    ports:
      - '3000:3000'
    volumes:
      - './.data/grafana:/var/lib/grafana'

  prometheus:
    container_name: 'prometheus'
    image: 'prom/prometheus'
    restart: 'unless-stopped'
    ports:
      - '9090:9090'
    volumes:
      - './prometheus:/etc/prometheus'
      - './.data/prometheus:/prometheus'

  blackbox-exporter:
    container_name: 'blackbox-exporter'
    image: 'prom/blackbox-exporter'
    restart: 'unless-stopped'
    ports:
      - '9115:9115'
    volumes:
      - './blackbox-exporter:/etc/blackbox_exporter'

  speedtest-exporter:
    container_name: 'speedtest-exporter'
    image: 'raeffs/speedtest-exporter'
    restart: 'unless-stopped'
    ports:
      - '9112:9112'

  pihole-exporter:
    container_name: 'pihole-exporter'
    image: 'ekofr/pihole-exporter:latest'
    restart: 'unless-stopped'
    ports:
      - '9617:9617'
    environment:
      PIHOLE_HOSTNAME: 'pihole'
      PIHOLE_PASSWORD: 'secure'
      INTERVAL: '30s'
      PORT: '9617'

  home-assistant:
    container_name: 'home-assistant'
    image: 'homeassistant/home-assistant:stable'
    restart: 'unless-stopped'
    volumes:
      - '${DATA_DIR:?err}/home-assistant/:/config/'
      - './home-assistant/configuration.yaml:/config/configuration.yaml:ro'
    environment:
      TZ: '${TIMEZONE}'
      DATABASE_CONNECTION: 'mysql://home-assistant-user:${HA_MYSQL_PASSWORD}@home-assistant-db/home-assistant-db?charset=utf8'
    depends_on:
      - 'home-assistant-db'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.home-assistant.loadbalancer.server.port=8123'
      - 'traefik.http.routers.home-assistant.entrypoints=websecure'
      - 'traefik.http.routers.home-assistant.tls=true'

  home-assistant-db:
    container_name: 'home-assistant-db'
    image: 'mariadb:latest'
    restart: 'unless-stopped'
    volumes:
      - '${DATA_DIR:?err}/home-assistant-db/:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: 'home-assistant-db'
      MYSQL_USER: 'home-assistant-user'
      MYSQL_PASSWORD: '${HA_MYSQL_PASSWORD}'

  phpmyadmin:
    container_name: 'phpmyadmin'
    image: 'phpmyadmin:latest'
    restart: 'unless-stopped'
    environment:
      PMA_HOSTS: 'home-assistant-db'
    depends_on:
      - 'home-assistant-db'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.phpmyadmin.loadbalancer.server.port=80'
      - 'traefik.http.routers.phpmyadmin.entrypoints=websecure'
      - 'traefik.http.routers.phpmyadmin.tls=true'

  watchtower:
    container_name: 'watchtower'
    image: 'containrrr/watchtower:latest'
    restart: 'unless-stopped'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    environment:
      TZ: '${TIMEZONE}'
      WATCHTOWER_CLEANUP: 'true'
      WATCHTOWER_MONITOR_ONLY: 'false'
      WATCHTOWER_SCHEDULE: '0 0 2 * * *'
      WATCHTOWER_NOTIFICATIONS: 'slack'
      WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL: '${WT_SLACK_URL}'

  portainer:
    container_name: 'portainer'
    image: 'portainer/portainer-ce'
    restart: 'unless-stopped'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '${DATA_DIR:?err}/portainer/:/data/'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.portainer.loadbalancer.server.port=9000'
      - 'traefik.http.routers.portainer.entrypoints=websecure'
      - 'traefik.http.routers.portainer.tls=true'

  dozzle:
    container_name: 'dozzle'
    image: 'amir20/dozzle:latest'
    restart: 'unless-stopped'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.dozzle.loadbalancer.server.port=8080'
      - 'traefik.http.routers.dozzle.entrypoints=websecure'
      - 'traefik.http.routers.dozzle.tls=true'

  demo:
    container_name: 'demo'
    image: 'nginxdemos/hello'
    restart: 'unless-stopped'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.demo.loadbalancer.server.port=80'
      - 'traefik.http.routers.demo.entrypoints=websecure'
      - 'traefik.http.routers.demo.tls=true'
