tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
  stores:
    default:
      defaultCertificate:
        certFile: /etc/certs/home.pem
        keyFile: /etc/certs/home.key
  certificates:
    - certFile: /etc/certs/home.pem
      keyFile: /etc/certs/home.key
    - certFile: /etc/certs/traefik.home.pem
      keyFile: /etc/certs/home.key
    - certFile: /etc/certs/pihole.home.pem
      keyFile: /etc/certs/home.key
    - certFile: /etc/certs/portainer.home.pem
      keyFile: /etc/certs/home.key
    - certFile: /etc/certs/dozzle.home.pem
      keyFile: /etc/certs/home.key
    - certFile: /etc/certs/prometheus.home.pem
      keyFile: /etc/certs/home.key
    - certFile: /etc/certs/gitea.home.pem
      keyFile: /etc/certs/home.key
    - certFile: /etc/certs/phpmyadmin.home.pem
      keyFile: /etc/certs/home.key
    - certFile: /etc/certs/home-assistant.home.pem
      keyFile: /etc/certs/home.key
    - certFile: /etc/certs/grafana.home.pem
      keyFile: /etc/certs/home.key
    - certFile: /etc/certs/hello.home.pem
      keyFile: /etc/certs/home.key
