name: Keycloak Checks

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main

jobs:
  keycloak-healthcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Install Volta
        uses: volta-cli/action@v4

      - name: Restore cached Yarn Dependencies
        uses: actions/cache@v5
        with:
          path: |
            **/node_modules
            ~/.yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Configure Keycloak
        run: yarn configure keycloak-postgres --use-defaults

      - name: Start Keycloak
        run: yarn up keycloak-postgres

      - name: Wait for Containers to be healthy
        uses: jaracogmbh/docker-compose-health-check-action@v1.0.0
        with:
          retry-interval: 5
          max-retries: 10
          compose-file: apps/keycloak/keycloak-postgres/docker-compose.yml
